#!/usr/bin/env python3
"""
Script to update company websites in the CSV file.
"""

import csv
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CSV_FILE = ROOT / 'h1b_companies_roles.csv'

# Known company website mappings
COMPANY_WEBSITES = {
    'Virtusa Corporation': 'https://www.virtusa.com',
    'Vmware INC': 'https://www.vmware.com',
    'Cgi Technologies And Solutions INC': 'https://www.cgi.com',
    'Mindtree Limited': 'https://www.mindtree.com',
    'USt Global INC': 'https://www.ust.com',
    'Servicenow INC': 'https://www.servicenow.com',
    'Ford Motor Company': 'https://www.ford.com',
    'Capital One Services LLC': 'https://www.capitalone.com',
    'Bank Of America Na': 'https://www.bankofamerica.com',
    'Hexaware Technologies INC': 'https://www.hexaware.com',
    'Mckinsey & Company INC United States': 'https://www.mckinsey.com',
    'Intuit INC': 'https://www.intuit.com',
    'Bytedance INC': 'https://www.bytedance.com',
    'Deloitte Tax LLP': 'https://www.deloitte.com',
    'Goldman Sachs Services LLC': 'https://www.goldmansachs.com',
    'Comcast Cable Communications LLC': 'https://www.comcast.com',
    'Morgan Stanley Services Group INC': 'https://www.morganstanley.com',
    'Advanced Micro Devices INC': 'https://www.amd.com',
    'Rivian Automotive LLC': 'https://www.rivian.com',
    'Optum Services INC': 'https://www.optum.com',
    'Amazon Data Services INC': 'https://aws.amazon.com',
    'University Of Michigan': 'https://www.umich.edu',
    'US Bank National Association': 'https://www.usbank.com',
    'American Express Travel Related Services Company INC': 'https://www.americanexpress.com',
    'Visa Technology & Operations LLC': 'https://www.visa.com',
    'Charter Communications INC': 'https://www.charter.com',
    'Blackrock Financial Management INC': 'https://www.blackrock.com',
    'T-Mobile USA INC': 'https://www.t-mobile.com',
    'Kpmg LLP': 'https://www.kpmg.com',
    'Hewlett Packard Enterprise Company': 'https://www.hpe.com',
    'Pricewaterhousecoopers LLP': 'https://www.pwc.com',
    'Fis Management Services LLC': 'https://www.fisglobal.com',
    'Mastech Digital Technologies INC': 'https://www.mastechdigital.com',
    'Wells Fargo Bank Na': 'https://www.wellsfargo.com',
    'Dfs Corporate Services LLC': 'https://www.dell.com',
    'General Motors Company': 'https://www.gm.com',
    'Micron Technology INC': 'https://www.micron.com',
    'Expedia INC': 'https://www.expedia.com',
    'Mayo Clinic': 'https://www.mayoclinic.org',
    'Amazoncom Services INC': 'https://www.amazon.com',
    'Doordash INC': 'https://www.doordash.com',
    'The Leland Stanford Jr University': 'https://www.stanford.edu',
    'Johns Hopkins University': 'https://www.jhu.edu',
    'Bloomberg LP': 'https://www.bloomberg.com',
    'The Boston Consulting Group INC': 'https://www.bcg.com',
    'Barclays Services CORP': 'https://www.barclays.com',
    'Western Digital Technologies INC': 'https://www.westerndigital.com',
    'Visa USA INC': 'https://www.visa.com',
    'Mastercard International Incorporated': 'https://www.mastercard.com',
    'Palo Alto Networks INC': 'https://www.paloaltonetworks.com',
    'Databricks INC': 'https://www.databricks.com',
    'Splunk INC': 'https://www.splunk.com',
    'Zoom Video Communications INC': 'https://www.zoom.us',
    'Dropbox INC': 'https://www.dropbox.com',
    'Slack Technologies INC': 'https://www.slack.com',
    'Houston Independent School District': 'https://www.houstonisd.org',
    'Confluent INC': 'https://www.confluent.io',
    'Snowflake INC': 'https://www.snowflake.com',
    'Cloudflare INC': 'https://www.cloudflare.com',
    'Okta INC': 'https://www.okta.com',
    'Fastly INC': 'https://www.fastly.com',
    'Hashicorp INC': 'https://www.hashicorp.com',
    'Elastic Nv': 'https://www.elastic.co',
    'Mongodb INC': 'https://www.mongodb.com',
    'Red Hat INC': 'https://www.redhat.com',
    'ServiceTitan INC': 'https://www.servicetitan.com',
    'Twitch Interactive INC': 'https://www.twitch.tv',
    'Audible INC': 'https://www.audible.com',
    'Ring INC': 'https://www.ring.com',
    'Zynga INC': 'https://www.zynga.com',
    'Square INC': 'https://www.square.com',
    'Block INC': 'https://www.block.xyz',
    'Hulu LLC': 'https://www.hulu.com',
    'Spotify USA INC': 'https://www.spotify.com',
    'Pinterest INC': 'https://www.pinterest.com',
    'Snap INC': 'https://www.snap.com',
    'Marriott International INC': 'https://www.marriott.com',
    'Home Depot Product Authority LLC': 'https://www.homedepot.com',
    'Target Enterprise INC': 'https://www.target.com',
    'Best Buy CO INC': 'https://www.bestbuy.com',
    'Costco Wholesale Corporation': 'https://www.costco.com',
    'Nordstrom INC': 'https://www.nordstrom.com',
    'Starbucks Coffee Company': 'https://www.starbucks.com',
    'Pepsico INC': 'https://www.pepsico.com',
    'Coca-Cola Company': 'https://www.coca-cola.com',
    'Procter & Gamble Company': 'https://www.pg.com',
    'Johnson & Johnson Services INC': 'https://www.jnj.com',
    'Pfizer INC': 'https://www.pfizer.com',
    'Merck Sharp & Dohme LLC': 'https://www.merck.com',
    'Novartis Institutes For Biomedical Research INC': 'https://www.novartis.com',
    'Bristol-Myers Squibb Company': 'https://www.bms.com',
    'Amgen INC': 'https://www.amgen.com',
    'Gilead Sciences INC': 'https://www.gilead.com',
    'Biogen INC': 'https://www.biogen.com',
    'Regeneron Pharmaceuticals INC': 'https://www.regeneron.com',
    'Illumina INC': 'https://www.illumina.com',
    'Janssen Research & Development LLC': 'https://www.janssen.com',
    'Vertex Pharmaceuticals Incorporated': 'https://www.vrtx.com',
    'Moderna INC': 'https://www.modernatx.com',
    'Thermo Fisher Scientific INC': 'https://www.thermofisher.com',
    'Zoetis INC': 'https://www.zoetis.com',
    'Alexion Pharmaceuticals INC': 'https://www.alexion.com',
    'Incyte Corporation': 'https://www.incyte.com',
    'Abbvie INC': 'https://www.abbvie.com',
    'Takeda Development Center Americas INC': 'https://www.takeda.com',
    'Sanofi US Services INC': 'https://www.sanofi.com',
    'Bayer US LLC': 'https://www.bayer.com',
    'Roche Molecular Systems INC': 'https://www.roche.com',
    'Abbott Laboratories': 'https://www.abbott.com',
    'Medtronic INC': 'https://www.medtronic.com',
    'Baxter International INC': 'https://www.baxter.com',
    'Stryker Corporation': 'https://www.stryker.com',
    'Boston Scientific Corporation': 'https://www.bostonscientific.com',
    'Intuitive Surgical Operations INC': 'https://www.intuitive.com',
    'Edwards Lifesciences LLC': 'https://www.edwards.com',
    'DaVita INC': 'https://www.davita.com',
    'Fresenius Medical Care': 'https://www.freseniusmedicalcare.com',
    'UnitedHealth Group INC': 'https://www.unitedhealthgroup.com',
    'Anthem INC': 'https://www.anthem.com',
    'Aetna Resources LLC': 'https://www.aetna.com',
    'Blue Cross Blue Shield Of Michigan': 'https://www.bcbsm.com',
    'Kaiser Foundation Health Plan': 'https://www.kaiserpermanente.org',
    'Humana INC': 'https://www.humana.com',
    'Cigna Health & Life Insurance Company': 'https://www.cigna.com',
    'Centene Management Company LLC': 'https://www.centene.com',
    'Molina Healthcare INC': 'https://www.molinahealthcare.com',
    'HCSC Health Insurance Services': 'https://www.bcbsil.com',
    'United Healthcare Services INC': 'https://www.unitedhealthcare.com',
    'Express Scripts Services CO': 'https://www.express-scripts.com',
    'CVS Health Corporation': 'https://www.cvshealth.com',
    'Walgreens CO': 'https://www.walgreens.com',
    'Rite Aid Corporation': 'https://www.riteaid.com',
    'McKesson Corporation': 'https://www.mckesson.com',
    'AmerisourceBergen Corporation': 'https://www.amerisourcebergen.com',
    'Cardinal Health INC': 'https://www.cardinalhealth.com',
    'Owen Healthcare INC': 'https://www.owenhealthcare.com',
    'Par Pharmaceutical Companies INC': 'https://www.parpharm.com',
    'Teva Pharmaceuticals USA INC': 'https://www.tevapharm.com',
    'Mylan INC': 'https://www.mylan.com',
    'Actavis INC': 'https://www.actavis.com',
    'Allergan INC': 'https://www.allergan.com',
    'Endo Pharmaceuticals': 'https://www.endo.com',
    'Valeant Pharmaceuticals International': 'https://www.bauschhealth.com',
    'Mallinckrodt Pharmaceuticals': 'https://www.mallinckrodt.com',
    'Sun Pharmaceutical Industries': 'https://www.sunpharma.com',
    'Lupin Pharmaceuticals INC': 'https://www.lupinpharmaceuticals.com',
    'Dr Reddys Laboratories INC': 'https://www.drreddys.com',
    'Aurobindo Pharma USA INC': 'https://www.aurobindousa.com',
    'Cipla USA INC': 'https://www.cipla.com',
    'Zydus Pharmaceuticals USA INC': 'https://www.zydususa.com',
    'Glenmark Pharmaceuticals USA INC': 'https://www.glenmarkpharma.com',
    'Torrent Pharmaceuticals INC': 'https://www.torrentpharma.com',
    'Wockhardt USA INC': 'https://www.wockhardtusa.com',
    'Cadila Healthcare USA INC': 'https://www.cadilapharmaceuticals.com',
    'Biocon INC': 'https://www.biocon.com',
    'Strides Pharma Science INC': 'https://www.strides.com',
    'NATCO Pharma USA INC': 'https://www.natcopharma.com',
    'Emcure Pharmaceuticals USA INC': 'https://www.emcureusa.com',
    'Taro Pharmaceuticals USA INC': 'https://www.taro.com',
    'Perrigo Company': 'https://www.perrigo.com',
    'Purdue Pharma': 'https://www.purduepharma.com',
    'Mallinckrodt Pharmaceuticals': 'https://www.mallinckrodt.com',
    'Jazz Pharmaceuticals': 'https://www.jazzpharma.com',
    'Horizon Pharma': 'https://www.horizonpharma.com',
    'Alkermes INC': 'https://www.alkermes.com',
    'Ironwood Pharmaceuticals': 'https://www.ironwoodpharma.com',
    'Acorda Therapeutics INC': 'https://www.acorda.com',
    'AcelRx Pharmaceuticals': 'https://www.acelrx.com',
    'Adamis Pharmaceuticals': 'https://www.adamispharmaceuticals.com',
    'Akorn INC': 'https://www.akorn.com',
    'Alembic Pharmaceuticals USA': 'https://www.alembicpharmaceuticals.com',
    'Amneal Pharmaceuticals LLC': 'https://www.amneal.com',
    'Apotex INC': 'https://www.apotex.com',
    'Ascend Laboratories': 'https://www.ascendlaboratories.com',
    'Bausch & Lomb': 'https://www.bausch.com',
    'Bayer HealthCare': 'https://www.bayer.com',
    'Bedford Laboratories': 'https://www.bedfordlabs.com',
    'Boehringer Ingelheim Pharmaceuticals INC': 'https://www.boehringer-ingelheim.com',
    'Braun Medical INC': 'https://www.bbraunusa.com',
    'Bristol Myers Squibb': 'https://www.bms.com',
    'Catalent': 'https://www.catalent.com',
    'Cephalon INC': 'https://www.cephalon.com',
    'Chiron Corporation': 'https://www.chiron.com',
    'Cipla USA INC': 'https://www.cipla.com',
    'Colgate-Palmolive Company': 'https://www.colgate.com',
    'Concordia Pharmaceuticals INC': 'https://www.concordiarx.com',
    'ConvaTec INC': 'https://www.convatec.com',
    'Covidien LP': 'https://www.covidien.com',
    'Crest Laboratories INC': 'https://www.crestlab.com',
    'Daiichi Sankyo INC': 'https://www.daiichisankyo.com',
    'Dermira INC': 'https://www.dermira.com',
    'Eisai INC': 'https://www.eisai.com',
    'Elan Corporation': 'https://www.elan.com',
    'Endo Pharmaceuticals': 'https://www.endo.com',
    'Eurand Pharmaceuticals': 'https://www.eurand.com',
    'Ferrer Pharma': 'https://www.ferrer.com',
    'Ferring Pharmaceuticals': 'https://www.ferring.com',
    'Forest Laboratories': 'https://www.forestlaboratories.com',
    'Fresenius Kabi': 'https://www.freseniuskabi.com',
    'Galderma Laboratories': 'https://www.galderma.com',
    'Genentech INC': 'https://www.gene.com',
    'Generics Pharmaceutical': 'https://www.genericspharma.com',
    'Gilead Sciences': 'https://www.gilead.com',
    'Glenmark Pharmaceuticals': 'https://www.glenmarkpharma.com',
    'GRIFOLS USA': 'https://www.grifols.com',
    'H. Lundbeck A/S': 'https://www.lundbeck.com',
    'Hikma Pharmaceuticals': 'https://www.hikma.com',
    'Hospira INC': 'https://www.hospira.com',
    'Ipsen Pharma': 'https://www.ipsen.com',
    'Ironwood Pharmaceuticals': 'https://www.ironwoodpharma.com',
    'Ivenix INC': 'https://www.ivenix.com',
    'Jazz Pharmaceuticals': 'https://www.jazzpharma.com',
    'Jubilant Cadista Pharmaceuticals': 'https://www.jubilantcadista.com',
    'King Pharmaceuticals': 'https://www.kingpharm.com',
    'KVK-Tech INC': 'https://www.kvktech.com',
    'Laboratories Mylan': 'https://www.mylan.com',
    'Lannett Company': 'https://www.lannett.com',
    'Ligand Pharmaceuticals': 'https://www.ligand.com',
    'Lilly USA LLC': 'https://www.lilly.com',
    'Lupin Pharmaceuticals': 'https://www.lupinpharmaceuticals.com',
    'Marinus Pharmaceuticals': 'https://www.marinuspharma.com',
    'Melinta Therapeutics': 'https://www.melinta.com',
    'Merck & Company': 'https://www.merck.com',
    'Merz USA': 'https://www.merzusa.com',
    'MGI Pharma INC': 'https://www.mgipharma.com',
    'Mission Pharmacal Company': 'https://www.missionpharmacal.com',
    'Momenta Pharmaceuticals': 'https://www.momentapharma.com',
    'Morton Grove Pharmaceuticals': 'https://www.mgpharma.com',
    'Mylan Pharmaceuticals INC': 'https://www.mylan.com',
    'Natco Pharma USA INC': 'https://www.natcopharma.com',
    'Nektar Therapeutics': 'https://www.nektar.com',
    'Nevro Corporation': 'https://www.nevro.com',
    'Northstar Rx LLC': 'https://www.northstarrx.com',
    'Noven Pharmaceuticals': 'https://www.noven.com',
    'Novo Nordisk INC': 'https://www.novonordisk-us.com',
    'Noxxon Pharma AG': 'https://www.noxxon.com',
    'Nucryst Pharmaceuticals': 'https://www.nucryst.com',
    'Novartis Pharmaceuticals': 'https://www.novartis.com',
    'Oasis Pharmaceuticals': 'https://www.oasispharma.com',
    'Ocugen INC': 'https://www.ocugen.com',
    'Octapharma USA': 'https://www.octapharmausa.com',
    'Orexigen Therapeutics': 'https://www.orexigen.com',
    'Otsuka America Pharmaceutical INC': 'https://www.otsuka-us.com',
    'Pacira Pharmaceuticals': 'https://www.pacira.com',
    'Par Pharmaceutical': 'https://www.parpharm.com',
    'Parke-Davis': 'https://www.parke-davis.com',
    'P&G Pharmaceuticals': 'https://www.pg.com',
    'Pfizer INC': 'https://www.pfizer.com',
    'PharmaForce': 'https://www.pharmaforce.com',
    'Pharmasset INC': 'https://www.pharmasset.com',
    'Pharmacia Corporation': 'https://www.pharmacia.com',
    'Pharmacosmos': 'https://www.pharmacosmos.com',
    'Pharmavite': 'https://www.pharmavite.com',
    'Pharmacyclics INC': 'https://www.pharmacyclics.com',
    'Pharmion Corporation': 'https://www.pharmion.com',
    'Phoenix Labs': 'https://www.phoenix-labs.com',
    'Piramal Healthcare': 'https://www.piramal.com',
    'Pliant Therapeutics': 'https://www.pliantrx.com',
    'Procter & Gamble': 'https://www.pg.com',
    'PureTech Health': 'https://www.puretechhealth.com',
    'Quidel Corporation': 'https://www.quidel.com',
    'Radius Health INC': 'https://www.radiuspharm.com',
    'Rapala USA': 'https://www.rapala.com',
    'Recordati Rare Diseases': 'https://www.recordati.com',
    'Regeneron Pharmaceuticals': 'https://www.regeneron.com',
    'ReGenX Biosciences': 'https://www.regenxbio.com',
    'Relmada Therapeutics': 'https://www.relmada.com',
    'Reliant Pharmaceuticals': 'https://www.reliantpharmaceuticals.com',
    'Revance Therapeutics': 'https://www.revance.com',
    'Revatio Pharmaceuticals': 'https://www.revatiopharma.com',
    'Rhodes Pharmaceuticals': 'https://www.rhodespharmaceuticals.com',
    'Rigel Pharmaceuticals': 'https://www.rigel.com',
    'Rigel Pharmaceuticals INC': 'https://www.rigel.com',
    'Roche Laboratories': 'https://www.roche.com',
    'Romark Laboratories': 'https://www.romark.com',
    'Sagent Pharmaceuticals': 'https://www.sagentpharma.com',
    'Salix Pharmaceuticals': 'https://www.salix.com',
    'Sanofi-Aventis': 'https://www.sanofi.com',
    'Santarus INC': 'https://www.santarus.com',
    'Schering-Plough': 'https://www.schering-plough.com',
    'SciClone Pharmaceuticals': 'https://www.sciclone.com',
    'Seattle Genetics': 'https://www.seattlegenetics.com',
    'Sequus Pharmaceuticals': 'https://www.sequus.com',
    'Serono INC': 'https://www.serono.com',
    'Shire Pharmaceuticals': 'https://www.shire.com',
    'SIGA Technologies': 'https://www.siga.com',
    'Sigma-Aldrich Corporation': 'https://www.sigmaaldrich.com',
    'SkyePharma INC': 'https://www.skyepharma.com',
    'Solvay Pharmaceuticals': 'https://www.solvaypharmaceuticals.com',
    'Somaxon Pharmaceuticals': 'https://www.somaxon.com',
    'Spectrum Pharmaceuticals': 'https://www.sppirx.com',
    'Squibb Corporation': 'https://www.squibb.com',
    'Staxyn Pharmaceuticals': 'https://www.staxyn.com',
    'Steris Corporation': 'https://www.steris.com',
    'Sunovion Pharmaceuticals': 'https://www.sunovion.com',
    'Supernus Pharmaceuticals': 'https://www.supernus.com',
    'Takeda Pharmaceuticals': 'https://www.takeda.com',
    'Talecris Biotherapeutics': 'https://www.talecris.com',
    'Targacept INC': 'https://www.targacept.com',
    'Taro Pharmaceuticals': 'https://www.taro.com',
    'Teva Pharmaceutical': 'https://www.tevapharm.com',
    'The Medicines Company': 'https://www.themedicinescompany.com',
    'Theravance Biopharma': 'https://www.theravance.com',
    'Third Rock Ventures': 'https://www.thirdrockventures.com',
    'Threshold Pharmaceuticals': 'https://www.thresholdpharm.com',
    'Tibotec Therapeutics': 'https://www.tibotec.com',
    'Tobira Therapeutics': 'https://www.tobiratx.com',
    'Tolmar INC': 'https://www.tolmar.com',
    'Tranzyme Pharma': 'https://www.tranzyme.com',
    'Tris Pharma': 'https://www.trispharma.com',
    'UCB INC': 'https://www.ucb.com',
    'Ucyclyd Pharma': 'https://www.ucyclyd.com',
    'United Therapeutics Corporation': 'https://www.unither.com',
    'Valeant Pharmaceuticals': 'https://www.bauschhealth.com',
    'Vanda Pharmaceuticals': 'https://www.vandapharmaceuticals.com',
    'Vertex Pharmaceuticals': 'https://www.vrtx.com',
    'Vifor Pharma': 'https://www.viforpharma.com',
    'ViiV Healthcare': 'https://www.viivhealthcare.com',
    'ViroPharma INC': 'https://www.viropharma.com',
    'Vitae Pharmaceuticals': 'https://www.vitaepharma.com',
    'Vivus INC': 'https://www.vivus.com',
    'Wockhardt USA': 'https://www.wockhardtusa.com',
    'Wyeth Pharmaceuticals': 'https://www.wyeth.com',
    'XenoPort INC': 'https://www.xenoport.com',
    'Xoma Corporation': 'https://www.xoma.com',
    'Yamada Corporation': 'https://www.yamada.com',
    'Zogenix INC': 'https://www.zogenix.com',
    'Zydus Pharmaceuticals USA INC': 'https://www.zydususa.com',
}

def update_csv():
    """Read CSV, update websites, and write back."""
    
    # Read all rows
    rows = []
    with open(CSV_FILE, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        headers = reader.fieldnames
        
        for row in reader:
            # Update website if missing and we have it
            company = row['Company Name']
            if (not row['Website'] or row['Website'].strip() == '') and company in COMPANY_WEBSITES:
                row['Website'] = COMPANY_WEBSITES[company]
                print(f'Updated: {company} -> {row["Website"]}')
            
            rows.append(row)
    
    # Write updated CSV
    with open(CSV_FILE, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        writer.writerows(rows)
    
    print(f'\nDone! Updated {CSV_FILE}')

if __name__ == '__main__':
    update_csv()

